name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Prepare Deployment Package
      run: |
        zip -r function.zip . -x "*.git*" "*.github*" "*.zip"
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload Lambda Function to AWS
      run: aws lambda update-function-code --function-name mutual-funds-top10-holdings-tracker --zip-file fileb://function.zip